tag: "dino"

eval_checkpoint: "/vision-nfs/isola/projects/shobhita/code/dreamsim/dreamsim_steph/new_checkpoints/lora_single_dino_vitb16_cls_lora_lr_0.0003_batchsize_32_wd_0.0_hiddensize_1_margin_0.05_lorar_16_loraalpha_32.0_loradropout_0.2/lightning_logs/version_0/checkpoints/dino_vitb16_lora/"
eval_checkpoint_cfg: "/vision-nfs/isola/projects/shobhita/code/dreamsim/dreamsim_steph/new_checkpoints/lora_single_dino_vitb16_cls_lora_lr_0.0003_batchsize_32_wd_0.0_hiddensize_1_margin_0.05_lorar_16_loraalpha_32.0_loradropout_0.2/lightning_logs/version_0/config.yaml"
load_dir: "/vision-nfs/isola/projects/shobhita/code/dreamsim/models"

baseline_model: "dino_vitb16"
baseline_feat_type: "cls"
baseline_stride: "16"

nights_root: "/vision-nfs/isola/projects/shobhita/data/nights"
bapps_root: "/vision-nfs/isola/projects/shobhita/data/2afc/val"
things_root: "/vision-nfs/isola/projects/shobhita/data/things/things_src_images"
things_file: "/vision-nfs/isola/projects/shobhita/data/things/things_valset.txt"
df2_root: "/data/vision/phillipi/perception/data/df2_org3/"
df2_gt: "/data/vision/phillipi/perception/code/repalignment/configs/df2_gt.json"

batch_size: 256
num_workers: 10